### ISSUE TITLE
ranker: verbosity error

### ISSUE THREAD

**Issue by dirknbr** [bigdong89/xgboostExtension#20]
The fit function leads to a parameter error, maybe this has to do with different version of xgboost

```
Traceback (most recent call last):
  File "/home/dnachbar/python/lightgbm/xgbrank.py", line 32, in <module>
    ranker.fit(X, y, eval_metric=['ndcg', 'map@5-'])
  File "/home/dnachbar/.local/lib/python3.7/site-packages/xgboostextension/xgbranker.py", line 102, in fit
    verbose_eval=verbose, xgb_model=xgb_model)
  File "/home/dnachbar/.local/lib/python3.7/site-packages/xgboost/training.py", line 209, in train
    xgb_model=xgb_model, callbacks=callbacks)
  File "/home/dnachbar/.local/lib/python3.7/site-packages/xgboost/training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "/home/dnachbar/.local/lib/python3.7/site-packages/xgboost/core.py", line 1249, in update
    dtrain.handle))
  File "/home/dnachbar/.local/lib/python3.7/site-packages/xgboost/core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Parameter format for verbosity expect int but value='True'
```

**Comment by nbarbosa-git** [comment]
same issue
