### ISSUE TITLE
run xgbranker_example error

### ISSUE THREAD

**Issue by lzhw520110** [bigdong89/xgboostExtension#4]
win7  py2.7  xgboost 0.7
when run  xgbranker_example,   I get error as this
![image](https://user-images.githubusercontent.com/21998820/35896136-c71e4d78-0bf5-11e8-8a45-8ee89d273b56.png)
![image](https://user-images.githubusercontent.com/21998820/35896192-14e43cfc-0bf6-11e8-93dc-3aa8fdd4576f.png)
I add 'n_jobs' and 'random_state' to class XGBRanker.__init__(), This error dispeared, but I get a new error as this

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    dtrain.handle))
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\xgboost-0.7-py2.7.egg\xgboost\core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: Invalid Parameter format for seed expect int but value='None'

When I set seed=0 in class XGBRanker.__init__() and run xgbranker_example again,  get a new error as this:

[11:10:29] dmlc-core/include/dmlc/./logging.h:300: [11:10:29] src/tree/updater_colmaker.cc:657: Check failed: param.colsample_bylevel > 0U (0 vs. 0) colsample_bylevel cannot be zero.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    xgb_model=xgb_model, callbacks=callbacks)
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\xgboost-0.7-py2.7.egg\xgboost\training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\xgboost-0.7-py2.7.egg\xgboost\core.py", line 898, in update
    dtrain.handle))
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\xgboost-0.7-py2.7.egg\xgboost\core.py", line 130, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: [11:10:29] src/tree/updater_colmaker.cc:657: Check failed: param.colsample_bylevel > 0U (0 vs. 0) colsample_bylevel cannot be zero.
>>>   File "C:\Users\Lenovo\Anaconda2\lib\site-packages\xgboost-0.7-py2.7.egg\xgboost\training.py", line 204, in train
    xgb_model=None)
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\xgboost_ranking-0.6.1-py2.7.egg\xgboostextension\xgbranker.py", line 101, in fit
    ranker.fit(X, y, [25, 25, 25, 25], eval_metric=['ndcg', 'map@5-'])
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\Lenovo\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "D:/0rqalpha/quantOS/xgbRanker/demo.py", line 22, in <module>

I have no idea about this error!

**Comment by bigdong89** [comment]
I don't know what happened.
But it's obvious that recently xgboost-0.7 is released but I haven't upgrade my package.
Switch your xgboost to 0.6, it will be OK.
I will update it to 0.7  work with new version of xgboost when I'm free.
Good luck!

**Comment by FlorisHoogenboom** [comment]
I've encounterd the same issue. I've made PR https://github.com/bigdong89/xgboostExtension/pull/5 for the upgrade to V0.7.

The reason for the error lies in the fact that the get_xgb_params function uses the __init__ signature to get the parameters. Since this signature has changed in XGBoost v0.7 this error was raised.

**Comment by bigdong89** [comment]
Thanks, Floris! Codes are merged for 0.7!
